name: Publish webssh-sh to PyPI
on: 
  push:
    branches:
        - main
jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TOKEN }}
          TWINE_PASSWORD: ""
        run: |
          python3 -m build
          twine upload dist/*