name: Publish webssh-sh to PyPI
on: 
  push:
    branches:
        - main
        - develop
    tags:
        - 'v*'
jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine
      - name: Build
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TOKEN }}
          TWINE_PASSWORD: ""
        run: |
          python3 -m build
          twine check dist/*
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}